language: node_js
node_js:
- '0.12'
before_install:
- npm install -g gulp
- rvm use 1.9.3
- gem install bundler
- bundle install
script: gulp build
deploy:
  provider: heroku
  api_key:
    secure: V0/WcXnskrHv/S9pclL+AUDXe4Q5jJLUyuBcBATWpgcp/ooLgEgyMuTNQC2mkYhd8/iJy3NmK1ERpWA8BwvIxdCecWBtUItqRiDsHcOaK1LDLxjjp1pFExstC82sxKmkLfzT2DDALSLzUs6p3CPzEJLPAiWxGsa+cOWVXdo/qMM=
  skip_cleanup: true
  buildpack: nodejs
  app:
    master: dev-wikifish
    production: appwikifish
