language: node_js
node_js:
- '0.12'
before_install:
- npm install -g gulp
- rvm use 1.9.3
- gem install bundler
- bundle install
script: gulp build
deploy:
  provider: heroku
  api_key: a0d003c6-a8d5-4dfc-b986-54d17b602cf7
  skip_cleanup: true
  buildpack: nodejs
  app:
    master: wikifish-site
